### ISSUE TITLE
Exception in gpu_hist: NCCL failure :unhandled cuda error

### ISSUE THREAD

**Issue by zhnin** [NVIDIA/spark-xgboost-examples#11]
Hi
i am trying to run spark-xgboost-examples with scala and python
- YARN for Scala
- YARN for Python 

but i got the same error ,
```sh
ml.dmlc.xgboost4j.java.XGBoostError: [12:56:19] /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/updater_gpu_hist.cu:1490: 
Exception in gpu_hist: NCCL failure :unhandled cuda error /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/../common/device_helpers.cuh(1061)
```

**My environment:**
```sh
OS      : Ubuntu 18.04.4
GPU     : 4*V100 (16G)
Driver  : 418.87.01
CUDA  : V10.1.243
NCCL  : 2.4.7-1+cuda10.1

java  : java-1.8.0-openjdk-amd64
scala : scala-2.12.10
hadoop : hadoop-3.1.3
spark : spark-3.0.0-bin-hadoop3.2
```
- I hava set yarn with isolation:   https://nvidia.github.io/spark-rapids/docs/getting-started.html#yarn-313-with-isolation-and-gpu-scheduling-enabled
- nccl version
```sh
root@master:~# dpkg -l | grep nccl
ii  libnccl-dev                             2.4.7-1+cuda10.1                                amd64        NVIDIA Collectives Communication Library (NCCL) Development Files
ii  libnccl2                                2.4.7-1+cuda10.1                                amd64        NVIDIA Collectives Communication Library (NCCL) Runtime
ii  nccl-repo-ubuntu1804-2.4.7-ga-cuda10.1  1-1                                             amd64        nccl repository configuration files

```

**spark-submit command**
```sh
export DATA_PATH=hdfs:/tmp/xgboost4j_spark/data
export JARS_PATH=hdfs:/tmp/xgboost4j_spark/jars
export EXAMPLE_CLASS=com.nvidia.spark.examples.mortgage.GPUMain
export JAR_EXAMPLE=${JARS_PATH}/sample_xgboost_apps-0.2.2-jar-with-dependencies.jar
export JAR_RAPIDS=${JARS_PATH}/rapids-4-spark_2.12-0.1.0.jar

${SPARK_HOME}/bin/spark-submit                                                    \
 --conf spark.plugins=com.nvidia.spark.SQLPlugin                                \
 --conf spark.rapids.memory.gpu.pooling.enabled=false                           \
 --conf spark.executor.resource.gpu.amount=1                                    \
 --conf spark.task.resource.gpu.amount=1                                        \
 --conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh       \
 --conf spark.task.cpus=1                                                       \
 --files $SPARK_HOME/examples/src/main/scripts/getGpusResources.sh              \
 --jars ${JAR_RAPIDS},${JAR_EXAMPLE}                                            \
 --master yarn                                                                  \
 --deploy-mode client                                                           \
 --num-executors 2                                                              \
 --executor-cores 1                                                             \
 --driver-memory 4g                                                             \
 --executor-memory 8g                                                           \
 --class ${EXAMPLE_CLASS}                                                       \
 ${JAR_EXAMPLE}                                                                 \
 -dataPath=train::${DATA_PATH}/mortgage/csv/train/mortgage_train_merged.csv     \
 -dataPath=trans::${DATA_PATH}/mortgage/csv/test/mortgage_eval_merged.csv       \
 -format=csv                                                                    \
 -numWorkers=2                                                                  \
 -treeMethod=gpu_hist                                                           \
 -numRound=100                                                                  \
 -maxDepth=8   
```

**container/stderr**
```sh
2020-07-06 12:01:41,790 INFO executor.YarnCoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@master:37781
2020-07-06 12:01:41,803 INFO resource.ResourceDiscoveryScriptPlugin: Discovering resources for gpu with script: ./getGpusResources.sh
2020-07-06 12:01:41,938 INFO resource.ResourceUtils: ==============================================================
2020-07-06 12:01:41,939 INFO resource.ResourceUtils: Resources for spark.executor:
gpu -> [name: gpu, addresses: 0]
2020-07-06 12:01:41,939 INFO resource.ResourceUtils: ==============================================================
2020-07-06 12:01:42,060 INFO executor.YarnCoarseGrainedExecutorBackend: Successfully registered with driver
2020-07-06 12:01:42,064 INFO executor.Executor: Starting executor ID 1 on host master
2020-07-06 12:01:42,152 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44915.
2020-07-06 12:01:42,152 INFO netty.NettyBlockTransferService: Server created on master:44915
2020-07-06 12:01:42,154 INFO storage.BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2020-07-06 12:01:42,162 INFO storage.BlockManagerMaster: Registering BlockManager BlockManagerId(1, master, 44915, None)
2020-07-06 12:01:42,174 INFO storage.BlockManagerMaster: Registered BlockManager BlockManagerId(1, master, 44915, None)
2020-07-06 12:01:42,176 INFO storage.BlockManager: Initialized BlockManager: BlockManagerId(1, master, 44915, None)
2020-07-06 12:01:42,209 INFO rapids.RapidsExecutorPlugin: Initializing memory from Executor Plugin
2020-07-06 12:01:50,020 INFO rapids.GpuDeviceManager: Initializing RMM  14517.44921875 MB on gpuId 0
2020-07-06 12:01:50,035 INFO plugin.ExecutorPluginContainer: Initialized executor component for plugin com.nvidia.spark.SQLPlugin.
2020-07-06 12:01:50,135 INFO executor.YarnCoarseGrainedExecutorBackend: Got assigned task 0
2020-07-06 12:01:50,144 INFO executor.Executor: Running task 0.0 in stage 0.0 (TID 0)
2020-07-06 12:01:50,250 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 1 with 1 pieces (estimated total size 4.0 MiB)
2020-07-06 12:01:50,302 INFO client.TransportClientFactory: Successfully created connection to master/172.16.2.17:37137 after 2 ms (0 ms spent in bootstraps)
2020-07-06 12:01:50,349 INFO memory.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 7.4 KiB, free 4.1 GiB)
2020-07-06 12:01:50,359 INFO broadcast.TorrentBroadcast: Reading broadcast variable 1 took 109 ms
2020-07-06 12:01:50,433 INFO memory.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 14.6 KiB, free 4.1 GiB)

2020-07-06 12:01:50,812 INFO datasources.FileScanRDD: Reading File path: hdfs://master:9000/tmp/xgboost4j_spark/data/mortgage/csv/train/mortgage_train_merged.csv, range: 0-993993, partition values: [empty row]
2020-07-06 12:01:50,814 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 0 with 1 pieces (estimated total size 4.0 MiB)
2020-07-06 12:01:50,824 INFO memory.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 43.2 KiB, free 4.1 GiB)
2020-07-06 12:01:50,827 INFO broadcast.TorrentBroadcast: Reading broadcast variable 0 took 13 ms
2020-07-06 12:01:50,865 INFO memory.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 600.3 KiB, free 4.1 GiB)
2020-07-06 12:01:51,592 INFO executor.Executor: Finished task 0.0 in stage 0.0 (TID 0). 2866 bytes result sent to driver
2020-07-06 12:01:51,643 INFO executor.YarnCoarseGrainedExecutorBackend: Got assigned task 1
2020-07-06 12:01:51,643 INFO executor.Executor: Running task 0.0 in stage 1.0 (TID 1)
2020-07-06 12:01:51,648 INFO spark.MapOutputTrackerWorker: Updating epoch to 1 and clearing cache
2020-07-06 12:01:51,666 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 2 with 1 pieces (estimated total size 4.0 MiB)
2020-07-06 12:01:51,673 INFO memory.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 5.6 KiB, free 4.1 GiB)
2020-07-06 12:01:51,675 INFO broadcast.TorrentBroadcast: Reading broadcast variable 2 took 8 ms
2020-07-06 12:01:51,676 INFO memory.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 9.8 KiB, free 4.1 GiB)
2020-07-06 12:01:51,847 INFO spark.MapOutputTrackerWorker: Don't have map outputs for shuffle 0, fetching them
2020-07-06 12:01:51,848 INFO spark.MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@master:37781)
2020-07-06 12:01:51,940 INFO spark.MapOutputTrackerWorker: Got the output locations
2020-07-06 12:01:52,092 INFO storage.ShuffleBlockFetcherIterator: Getting 1 (34.9 KiB) non-empty blocks including 1 (34.9 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
2020-07-06 12:01:52,093 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 13 ms
2020-07-06 12:01:52,105 INFO XGBoostSpark: XGboost GPU training using device: 0
2020-07-06 12:01:52,251 INFO java.DMatrix: load XGBoost libs
2020-07-06 12:01:52,257 INFO java.EnvironmentDetector: Found CUDA version from /usr/local/cuda/version.txt: 10.1.243
2020-07-06 12:01:52,257 INFO java.NativeLibLoader: found folder cuda10.1/ for CUDA 10.1.243
2020-07-06 12:01:57,055 ERROR XGBoostSpark: XGBooster worker 0 has failed due to
ml.dmlc.xgboost4j.java.XGBoostError: [12:01:57] /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/updater_gpu_hist.cu:1490: 
Exception in gpu_hist: NCCL failure :unhandled cuda error /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/../common/device_helpers.cuh(1061)

Stack trace:
  [bt] (0) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x35) [0x7f86edec2e35]
  [bt] (1) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x15a6) [0x7f86ee146076]
  [bt] (2) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x4e3) [0x7f86edf583e3]
  [bt] (3) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0xc29) [0x7f86edf5a5e9]
  [bt] (4) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x2b2) [0x7f86edf74302]
  [bt] (5) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(XGBoosterUpdateOneIter+0x29) [0x7f86edec6f49]
  [bt] (6) [0x7f8811018427]


        at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:50)
        at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:181)
        at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:190)
        at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:68)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.buildDistributedBooster(XGBoost.scala:210)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainPreferGpu$1(XGBoost.scala:592)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:362)
        at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1371)
        at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1298)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1362)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1186)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:360)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:311)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-07-06 12:01:57,059 WARN storage.BlockManager: Putting block rdd_10_0 failed due to exception ml.dmlc.xgboost4j.java.XGBoostError: [12:01:57] /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/updater_gpu_hist.cu:1490: Exception in gpu_hist: NCCL failure :unhandled cuda error /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/../common/device_helpers.cuh(1061)

Stack trace:
  [bt] (0) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x35) [0x7f86edec2e35]
  [bt] (1) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x15a6) [0x7f86ee146076]
  [bt] (2) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x4e3) [0x7f86edf583e3]
  [bt] (3) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0xc29) [0x7f86edf5a5e9]
  [bt] (4) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x2b2) [0x7f86edf74302]
  [bt] (5) /hadoop3/yarn/local/usercache/root/appcache/application_1594008041123_0001/container_1594008041123_0001_01_000002/tmp/libxgboost4j6390811092133043944.so(XGBoosterUpdateOneIter+0x29) [0x7f86edec6f49]
  [bt] (6) [0x7f8811018427]

.
2020-07-06 12:01:57,060 WARN storage.BlockManager: Block rdd_10_0 could not be removed as it was not found on disk or in memory
2020-07-06 12:01:57,067 ERROR executor.Executor: Exception in task 0.0 in stage 1.0 (TID 1)
ml.dmlc.xgboost4j.java.XGBoostError: [12:01:57] /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/updater_gpu_hist.cu:1490: Exception in gpu_hist: NCCL failure :unhandled cuda error /home/jenkinslc/workspace/llc-xgb-deploy-dev/src/tree/../common/device_helpers.cuh(1061)

```

**Comment by wbo4958** [comment]
Hi @zhnin The **NCCL** error may not be truly NCCL error,  
Although the NCCL version of your nodes was* the same* with the xgboost jars, we still need to check if the issue was caused by NCCL. 
So Could you run in a single node with a single xgboost worker and check if it can run?

**Comment by firestarman** [comment]
@zhnin Have you set up your Yarn nodes for GPU resources ? Pls refer to https://hadoop.apache.org/docs/r3.1.0/hadoop-yarn/hadoop-yarn-site/UsingGpus.html

**Comment by zhnin** [comment]
> Hi @zhnin The **NCCL** error may not be truly NCCL error,
> Although the NCCL version of your nodes was* the same* with the xgboost jars, we still need to check if the issue was caused by NCCL.
> So Could you run in a single node with a single xgboost worker and check if it can run?

My test environment has set master(resourcemanager) and worker(nodemanager) in a single node
- when i set "num-executors=1  numWorkers=1", it work well and one gpu used
- when i set "num-executors=2  numWorkers=2", it would have a "nccl error", 

from containers log i found 
- container has create success(one container with one gpu and each GPU "Initializing RMM" already done)
- each container has load files from datasource
- xgboost workers should created success: containers_1-> xgbooster worker 0, containers_2 -> xgboost worker 1
- from "ERROR Stack trace": it looks like stage "booster update" got a error after first iter ?(i am not sure)

**Comment by zhnin** [comment]
> @zhnin Have you set up your Yarn nodes for GPU resources ? Pls refer to https://hadoop.apache.org/docs/r3.1.0/hadoop-yarn/hadoop-yarn-site/UsingGpus.html

yes, i have set 
- GPU scheduling
- GPU Isolation under non-Docker environment

i also did a spark-shell test (success): https://nvidia.github.io/spark-rapids/docs/getting-started.html#example-join-operation

**Comment by wbo4958** [comment]
Hi @zhnin, As we debugged offline, the issue was caused by some inappropriate yarn GPU isolation configurations. So I just closed this issue.

**Comment by KastanDay** [comment]
For future reference, my issues was not using my cluster's resource scheduler slurm/sbatch. 
Instead of `python xgboost_code.py` I need to schedule a job with a `.sb` file. Good luck.
